name: Twitch Live Status

env:
  TWITCH_USERNAME: luckyloottube
  LIVE_BANNER_IMAGE: https://github.com/LuckyLootTube/LuckyLootTube/blob/f74d0a4c2c664656395472003ffaacdb1d955528/GitHub_Twitch.png
  GITHUB_USERNAME: LuckyLootTube
  GITHUB_EMAIL: luckyloottube@gmail.com

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Check Twitch live status
      id: twitch-status
      run: |
        live_status=$(curl -s https://api.doras.to/links/twitch/${{ env.TWITCH_USERNAME }} | jq -r '.live')
        echo "live_status=$live_status" >> $GITHUB_OUTPUT

    - name: Update README
      env:
        LIVE_STATUS: ${{ steps.twitch-status.outputs.live_status }}
      run: |
        echo "Live Status: $LIVE_STATUS"
        if [ "$LIVE_STATUS" == "true" ]; then
          sed -i "1s|^|[![Twitch Live Banner](${{ env.LIVE_BANNER_IMAGE }})](https:\/\/www.twitch.tv\/${{ env.TWITCH_USERNAME }})\n|" README.md
        else
          sed -i "/\[!\[Twitch Live Banner\](${{ env.LIVE_BANNER_IMAGE }})\](https:\/\/www\.twitch\.tv\/${{ env.TWITCH_USERNAME }})/d" README.md
          echo "Removed Twitch Live Banner"
        fi

    - name: Check for changes
      id: check_changes
      run: |
        git diff README.md
        if [ -n "$(git status --porcelain README.md)" ]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.email "${{ env.GITHUB_EMAIL }}"
        git config --global user.name "${{ env.GITHUB_USERNAME }}"
        git add README.md
        git commit -m "Update Twitch Live Banner in README"
        git push
